export const apptConstants = {
    VIEW_APPOINTMENT: 'VIEW_APPOINTMENT',
    MAKE_APPOINTMENT: 'MAKE_APPOINTMENT',
    UPDATE_APPOINTMENT: 'UPDATE_APPOINTMENT',
    REMOVE_APPOINTMENT: 'REMOVE_APPOINTMENT',
}